name: gatk4-env
channels:
    - bioconda
    - conda-forge
    - defaults

dependencies:
    - bioconda::gatk4=4.1.4
    - r-base
    - r-optparse=1.3.2
    - r-getopt=1.20.0
    - r-data.table=1.10.4
    - r-ggplot2=2.2.1
    - r-gplots=2.17.0
    - r-gsalib=2.1    