name: CMD-WGS
channels:
    - bioconda
    - conda-forge
    - defaults

dependencies:
    - bioconda::picard=2.20.5
    - bioconda::samtools=1.9
    - bioconda::sambamba=0.7.0
    - bioconda::gatk4=4.1.3
    - bioconda::vcflib=1.0.0_rc2
    - bioconda::bcftools=1.9
    - bioconda::snpsift=4.3
    - bioconda::tabix=0.2.6
    - bioconda::htslib=1.9
    - bioconda::bedtools=2.28.0
    - bioconda::vcftools=0.1.16
    - bioconda::perl-vcftools-vcf=0.1.16
    - bioconda::vt=2015.11.10
    - bioconda::sentieon=201808.07
    - bioconda::expansionhunter=3.1.2
    - bioconda::delly=0.8.1
    - bioconda::manta=1.6.0
    - bioconda::lumpy-sv=0.3.0