Bootstrap:docker
From:nfcore/base

%labels
	MAINTAINER Viktor henmyr <viktor.henmyr@skane.se>
	DESCRIPTION Singularity container for CMD WGS pipeline
	VERSION 0.0.2

%environment
	PATH=/opt/conda/envs/CMD-WGS/bin:/opt/sentieon-genomics-201808.05/bin/:/opt/bin:/opt/conda/envs/py3-env/bin:$PATH
	PICARD_HOME=/opt/conda/envs/CMD-WGS/share/picard-2.20.5-0/
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/CMD-WGS/lib/site_perl/5.26.2/
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/CMD-WGS/lib/site_perl/5.26.2/x86_64-linux-thread-multi/
	export PERL5LIB=$PERL5LIB:/opt/bin/

%files
        genmod.patch /
	environment.yml /
	environment_py3.yml /
	../bin/ /opt
	/data/bnf/sw/sentieon/sentieon-genomics-201711.05 /opt
	../rank_models/ /
%post
	rm -rf /var/lib/apt/lists/*
	apt -y clean
	apt -y update

	/opt/conda/bin/conda env create -f /environment_py3.yml python=3
	/opt/conda/bin/conda clean -a
        . /opt/conda/bin/activate py3-env

	git clone https://github.com/bjhall/upd.git
	cd upd
	git checkout 6f34d2e1a890ef7f030a2bf1458b82453835bf27
	/opt/conda/envs/py3-env/bin/pip install --editable .

        git clone https://github.com/moonso/stranger.git
	cd stranger
	git checkout 48218c711d5dd9cf7ce61f0804a12b904cfb6338
	/opt/conda/envs/py3-env/bin/pip install --editable .

	git clone https://github.com/J35P312/SVDB
	cd SVDB
	git checkout 2.2.0
	/opt/conda/envs/py3-env/bin/pip install --editable .



	/opt/conda/bin/conda env create -f /environment.yml
	apt -y install libz-dev build-essential gettext cmake libxml2-dev libcurl4-openssl-dev libssl-dev make
	/opt/conda/envs/CMD-WGS/bin/cpanm Path::Tiny --force
	/opt/conda/envs/CMD-WGS/bin/cpanm MongoDB::Collection
	/opt/conda/envs/CMD-WGS/bin/cpanm JSON
        /opt/conda/envs/CMD-WGS/bin/pip install genmod
        patch /opt/conda/envs/CMD-WGS/lib/python2.7/site-packages/genmod/score_variants/compound_scorer.py /genmod.patch
	git clone https://github.com/piratical/Madeline_2.0_PDE.git
	cd Madeline_2.0_PDE
	./configure --with-include-gettext
	make
	make install
	cd ..

	git clone https://github.com/Clinical-Genomics-Lund/modify_vcf_scout.git
	cp modify_vcf_scout/modify_vcf_scout.pl /opt/bin/.
	git clone https://github.com/Clinical-Genomics-Lund/qc_sentieon.git
	cp qc_sentieon/qc_sentieon.pl /opt/bin/.


				